from typing import Literal

from pydantic import BaseModel, Field
from pydantic_settings import SettingsConfigDict

from photobooth import CONFIG_PATH
from photobooth.services.config.baseconfig import BaseConfig

from .models import StylePrompt


class ConnectionSettings(BaseModel):
    openai_api_key: str = Field(
        default="",
        description="OpenAI API key for DALL-E/GPT image processing. Obtain from https://platform.openai.com/account/api-keys",
    )

    openai_model: Literal["dall-e-2", "gpt-image-1", "gpt-image-1-mini", "gpt-image-1.5"] = Field(
        default="gpt-image-1",
        description="OpenAI model to use (dall-e-2, gpt-image-1).",
    )

    timeout_seconds: int = Field(
        default=120,
        ge=5,
        le=300,
        description="Timeout for AI API calls in seconds.",
    )


class ImageGenerationSettings(BaseModel):
    image_quality: Literal["auto", "high", "medium", "low"] = Field(
        default="auto",
        description="Quality of generated images. 'auto' lets the model choose the best quality. Only supported by GPT models.",
    )

    image_size: Literal["auto", "1024x1024", "1536x1024", "1024x1536", "256x256", "512x512", "1792x1024", "1024x1792"] = Field(
        default="auto",
        description="Size of generated images. 'auto' lets the model choose optimal size. Available sizes depend on the selected model.",
    )

    input_fidelity: Literal["high", "low"] = Field(
        default="low",
        description="Control how much effort the model exerts to match input image style and features. 'high' preserves more details but takes longer. Only supported by gpt-image-1 and gpt-image-1.5.",
    )

    output_format: Literal["png", "jpeg", "webp"] = Field(
        default="jpeg",
        description="Output format for generated images (GPT models only). PNG supports transparency, JPEG is smaller, WEBP offers good compression with quality.",
    )

    output_compression: int = Field(
        default=85,
        ge=0,
        le=100,
        description="Compression level (0-100%) for generated images when using JPEG or WebP format. Higher values = better quality but larger files. Only supported by GPT models.",
    )

    moderation: Literal["low", "auto"] = Field(
        default="auto",
        description="Control the content-moderation level for images generated by the GPT image models. Must be either low for less restrictive filtering or auto (default value).",
    )


class PluginBehaviorSettings(BaseModel):
    add_userselectable_filter: bool = Field(
        default=True,
        description="Add userselectable AI filters to the list the user can choose from. When enabled, all enabled style_prompts will be available for user selection.",
    )

    enable_fallback_on_error: bool = Field(
        default=True,
        description="If AI generation fails, return the original image instead of an error.",
    )

    cache_results: bool = Field(
        default=True,
        description="Cache AI-generated results to avoid regenerating the same image multiple times.",
    )


class FilterOpenAiConfig(BaseConfig):
    model_config = SettingsConfigDict(
        title="Open AI Filter Plugin Config",
        json_file=f"{CONFIG_PATH}plugin_filter_openai.json",
        env_prefix="filter-openai-",
    )

    connection: ConnectionSettings = ConnectionSettings()
    image_generation: ImageGenerationSettings = ImageGenerationSettings()
    plugin_behavior: PluginBehaviorSettings = PluginBehaviorSettings()

    # Style prompts for different filter types
    style_prompts: list[StylePrompt] = Field(
        default=[
            StylePrompt(style_name="cartoon", prompt="cartoon style, animated, colorful, disney-like illustration"),
            StylePrompt(style_name="sketch", prompt="pencil sketch, black and white drawing, artistic sketch"),
            StylePrompt(style_name="watercolor", prompt="watercolor painting, soft brush strokes, artistic"),
            StylePrompt(style_name="oil_painting", prompt="oil painting, classical art style, rich textures"),
            StylePrompt(style_name="vintage", prompt="vintage photography, sepia tones, retro aesthetic"),
            StylePrompt(style_name="cyberpunk", prompt="cyberpunk style, neon lights, futuristic, sci-fi aesthetic"),
            StylePrompt(style_name="fantasy", prompt="fantasy art, magical, ethereal, mystical atmosphere"),
            StylePrompt(style_name="anime", prompt="Redraw this portrait in a style similar to Howl's Moving Castle by Studio Ghibli."),
        ],
        description="Prompt templates for different AI filter styles. These guide the AI generation process.",
    )
